### ISSUE TITLE
Refactor TradeWidget: LimitOrder

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-v1-ui#1381]
The `TradeWidget` is one of the most important parts of the app, and it's highly coupled to hooks, apis, and has lot's of logics.

This issue suggest to do a refactor of the component, making reusable presentational components out of it and their respective stories in storybook.

## Why
* Latest PRs were a bit difficult to implement and verify because of the growing technical debt in this part
* It's not really easy to change the implementation of the services: i.e. if we want to change web3 for etherjs, or change some APIs we have this logics mixed with the component presentation, or change the app to allow bundling of transactions
* We cannot easily reuse the widget for v2.0 layout, or for spinning other UIs with small changes. i.e. An IDO specific interface
* It's not easy to use in story book, makes 
* High coupling between components. There's many components, but they depend on a "form" context
* Additionally, it has some legacy code and props that are not required any more.

## Tasks
For tackling this, we can do several PR, one proposal would be to break it in these:
* [x] **Common**(#1371): Makes some general purpose small components dumb, and move them to a namespace "compoents/common"
* [x]  **Price Suggestions** (#1373): Refactor Price Estimations, also rename it into "PriceSuggestions"
* [x]  **Limit Order Mockup**(#1382): Limit Order mocked structure: Start by creating a pure presentational component, where we will integrate the other smaller components. It will start adding the "PriceSuggestions" implemented in #1373
* [ ] **Limit Price**: Refactor Price, also rename it into "Price"
* [ ] **Order Amount**: Refactor order amounts (buy and sell)
* [ ] **Order Validity**: Refactor order validity and it's modal
* [ ] **Consolidate all components**: Consolidate components into the Limit Order component.
* [ ] **Refactor Trade Widget**: Refactor TradeWidget, and create component version of the LimitOrder that contains all the hooks and behaviours (and delegates to LimitOrder)

## After this refactor
This changes is at the same time setting up how we will be building components in the future. Clearly making them "dumb" and moving the logic out of them. After taking this component, and agreeing on how to structure the code now, it should be more clear how to structure all the components from the whole project.

**Comment by anxolin** [comment]
We'll continue with the refactors another time, now is OBA time :)

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/13
