### ISSUE TITLE
[Order book] Improvement: Pending Issues

### ISSUE THREAD

**Issue by Rafanator** [gnosis/gp-v1-ui#1473]
Here is a general list for the pending orderbook related tasks: 

**Fix some basic usability issues**
- [ ] Update orderbook automatically without the need to refresh
- [ ] Leave only +/- Buttons, remove `Reset` and `Full`
- [ ] Remove thumbnails on top of the graph

**Make it easier to read in all conditions**
- [ ] Have initial zoom out from the start 
- [ ] Detect Price Reference PR (see #1481 )
- [ ] Use PR to filter out outlier orders (see #1481 )
- [ ] Keep always the PR in the center when ZOOM IN (see #1481 )
- [ ] Draw a vertical line for the mid market price (see #1481 )

**Test and validate**
- [ ] Make sure all work as expected by creating EDGE cases in the storybook: We already created some examples that break the orderbook, we need to go further and really find all the edge cases and see that we have an acceptable representation
- [ ] Validate with traders that it really improves the current implementation

## Storybook
- CURRENT DEV: https://dex.dev.gnosisdev.com/storybook/?path=/story/orderbook-sample-data--liquid-market `current `
- ONGOING WORK: https://pr1426--dexreact.review.gnosisdev.com/storybook (`will be merged soon to a open PR branch until is ready to be merged in develop`)

## Not included
* Not included, but somehow related https://github.com/gnosis/dex-react/issues/1484

**Comment by anxolin** [comment]
@Rafanator "Detect min/max represented price" is a separate issue. Is it created already?

**Comment by anxolin** [comment]
@Rafanator I redefined the tasks, and provided some additional info. We'll be taking over this, finalize the proposal.
Thx for the help so far!

**Comment by alfetopito** [comment]
Closed in favor of https://github.com/gnosis/gp-ui/issues/11
